models:
  - name: openai-gpt
    provider: openai
    model: gpt-4o-mini
    api_key: ${env.OPENAI_API_KEY}

default_model: openai-gpt

# Opcional: aquí puedes definir atajos o prompts preconfigurados
prompts:
  auditoria:
    description: "Revisión técnica del proyecto"
    prompt: |
      Actúa como auditor técnico senior. Revisa toda la estructura, dependencias, scripts, documentación y configuración del repositorio.
